### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by dtruong27** [Kurenai7968/volume_controller#1]
In `SwiftVolumeControllerPlugin`, line 30:

`
let volume = arg?["volume"] as? Float
volumeObserver.setVolume(volume: volume!)
`

Crash for flutter version Flutter 2.0.1. when using `setVolume`.

`arg?["volume"]` is sent as Double, not Float.

**Comment by JiangJuHong** [comment]
I found a volume control plug-in that supports IOS and Android。[perfect_volume_control](https://github.com/JiangJuHong/FlutterPerfectVolumeControl)
