### ISSUE TITLE
ShowSystemUI = false not working

### ISSUE THREAD

**Issue by Tpow99** [Kurenai7968/volume_controller#15]
Hello, I just started using your package and it is working great! I am having an issue however getting the systemUI not to display on iOS 16. I have called the flag showSystemUI = false but it doesn't seem to change anything. Any thoughts? 

<img width="625" alt="image" src="https://user-images.githubusercontent.com/39915854/196749042-31c0bf28-7353-4c82-8277-d10d4a9590e7.png">

**Comment by Kurenai7968** [comment]
Thank you your question.

showSystemUI only support Android now. This method do not support iOS to hide the system UI
