### ISSUE TITLE
Volume Listener continues to listen after dispose is called

### ISSUE THREAD

**Issue by badrobot15** [Kurenai7968/volume_controller#3]
Static getter 'volumeListener' can't be accessed through an instance. This keeps this listener active even after dispose is called

**Comment by Kurenai7968** [comment]
This issue fixed.
You can use listener function to listening volume, and using removeListener function to cancel volume listening.

**Comment by Kurenai7968** [comment]
> @Kurenai7968 I m using version 1.0.0
> 
> ```
> StreamSubscription<double> _volumeSubscription;
>  @override
>   void initState() {
>     super.initState();
> _volumeSubscription = VolumeController.volumeListener.listen((volume) {
>         setState(() => _volumeListenerValue = volume);
>        
>       });
>       VolumeController.getVolume().then((volume) => _setVolumeValue = volume);
> }
> @override
>   void dispose() {
>  _volumeSubscription.cancel();
> }
> ```
> 
> Still vlimne lister continue listen even app closed and access the volume button. any help?

This issue is encountered in which os? android or iOS or both?

**Comment by lsethi-xoriant** [comment]
currently I m trying only android
