### ISSUE TITLE
Audio always mute after resume from background

### ISSUE THREAD

**Issue by dodatw** [Kurenai7968/volume_controller#4]
This is a very useful package. It works well on iOS 15.
But if I add the listener, I found a problem
``
Volume controller().listener()
``

After resuming from the background, the audio will no longer work.
Even we adjust the volume.

**Comment by husainazkas** [comment]
> I will update new version to solve this problem later.

Hello, is this problem has been fixed?

**Comment by SamiXSous** [comment]
@Kurenai7968 Any update?
